Exam_Helper/Controllers/QuestionsLibController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exam_Helper.ViewsModel;
using System.Web.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Exam_Helper.Controllers
{
    public class QuestionsLibController : Controller
    {
        //private readonly 
        DbContext _context = new DbContext();

        //public QuestionsLibController(DbContext context)
        //{
        //    _context = context;
        //}

        public QuestionsLibController()
        {
        }

        // GET: QuestionsLib
        public async Task<ActionResult> Index(string SearchString)
        {

            //var ques = from que in _context.Question
            //           select que; //await _context.Question.ToListAsync();
            var ques = _context.Question;
            if (!string.IsNullOrEmpty(SearchString))
                return View(await ques.Where(x => x.Title.Contains(SearchString)
                                 || x.Proof.Contains(SearchString)
                                 || x.TagIds.Contains(SearchString)
                                 || x.Definition.Contains(SearchString)).ToListAsync());
            else
                return View(await ques.ToListAsync());
        }

       

        // GET: QuestionsLib/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

           

            var question = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }

        // GET: QuestionsLib/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var tags = await _context.Tags.Select(x => new TagForQuestionCreatingModel()
            { Id = x.Id, Name = x.Title, IsSelected = false }).ToListAsync();
            
            return View(new ClassForQuestionCreatingModel() { question = new Question(), tags = tags});
        }

        // POST: QuestionsLib/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClassForQuestionCreatingModel obj)
        {
            if (ModelState.IsValid)
            {
                var StringTags = string.Join(";", obj.tags.Where(x=>x.IsSelected).Select(x=>x.Id));

                obj.question.CreationDate = DateTime.Now;
                obj.question.UpdateDate = DateTime.Now;
                obj.question.Author = "Admin";
                obj.question.TagIds = StringTags;
                _context.Add(obj.question);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(obj.question);
        }

        // GET: QuestionsLib/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var question = await _context.Question.FindAsync(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }

        // POST: QuestionsLib/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Question question)
        {
            if (id != question.Id)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var old = await _context.Question.AsNoTracking().FirstAsync(x => x.Id == id);
                    question.CreationDate = old.CreationDate;
                    question.UpdateDate = DateTime.Now;
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(question);
        }

        // GET: QuestionsLib/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var question = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }

        // POST: QuestionsLib/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Question.FindAsync(id);
            _context.Question.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult RedirectToTest(int id) //RedirectToActionResult
        {
            TempData["question_id"] = id;
            return RedirectToAction(nameof(Index), nameof(Tests));
        }

        private bool QuestionExists(int id)
        {
            return _context.Question.Any(e => e.Id == id);
        }
    }
}

Exam_Helper/Views/QuestionsLib/Create.cshtml
@model Exam_Helper.ViewsModel.ClassForQuestionCreatingModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h4>Question</h4>
    <hr />
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.question.Definition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question.Definition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question.Definition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question.Proof, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question.Proof, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question.Proof, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--Author-->
        <!--CreationDate-->
        <!--UpdateDate-->
        <div class="form-group">
            @Html.LabelFor(model => model.tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for (int i = 0; i < Model.tags.Count; i++)
                {
                    <li>
                        @Html.CheckBoxFor(model => Model.tags[i].IsSelected)
                        @Html.Label(Model.tags[i].Name)
                        @Html.HiddenFor(model => model.tags[i].Id)
                        @Html.HiddenFor(model => model.tags[i].Name)
                    </li>
                }
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-light" })
</div>

Exam_Helper/Views/QuestionsLib/Details.cshtml
@model Exam_Helper.Question

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Definition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Definition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proof)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proof)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TagIds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagIds)
        </dd>

    </dl>
</div>
<p>
    <!--@Html.ActionLink("Edit", "Edit", new { id = Model.Id })-->
    @Html.ActionLink("Back to List", "Index")
</p>

Exam_Helper/Views/QuestionsLib/Index.cshtml
@model IEnumerable<Exam_Helper.Question>
@{
    ViewData["Title"] = "Library Page";
}

<main class="container" style="padding-top: 3vh;">
    <div class="container">

        <div class="justify-content text-center h1">
            <span>Библиотека</span>
        </div>

        <hr color="brown" />

        <div class="d-flex  bd-highlight pt-3 pb-3">
            <!--
            <a asp-action="Create">
                <button type="button" class="btn btn-warning bd-highlight">Добавить Вопрос</button>
            </a>
                -->
            @Html.ActionLink("Добавить Вопрос", "Create", "QuestionsLib", new { type = "button" }, new { @class = "btn btn-warning bd-highlight" })
            <div class="form-group pt-3 pb-3 bd-highlight ml-auto p-2"></div>
            <span class="mr-3"> Поиск вопроса: </span>
            <form asp-controller="QuestionsLib" asp-action="Index">
                <input type="text" name="SearchString" class="form-control">
            </form>
        </div>
    </div>
    <!-- Массив вопросов, отображение потом настроим -->
    <table class="table">
        <thead>
            <tr>

                <th scope="col"> <span>@Html.DisplayNameFor(model => model.Definition)</span> </th>
                <th scope="col"> <span>@Html.DisplayNameFor(model => model.Title) </span></th>
                <th scope="col">tags</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> <span>@Html.DisplayFor(modelItem => item.Definition) </span></td>
                    <td> <span>@Html.DisplayFor(modelItem => item.Title) </span></td>
                    <td> <span>@Html.DisplayFor(modelItem => item.TagIds) </span></td>
                    <td>
                        <div class=" d-flex justify-content-center dropdown">
                            <button class="btn btn-light dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @Html.ActionLink("Details", "Details", "QuestionsLib", new { id = item.Id }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Tests", "RedirectToTest", "QuestionsLib", new { id = item.Id }, new { @class = "dropdown-item" })
                            </div>
                        </div>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</main>