Exam_Helper/Controllers/PacksLibController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.EntityFrameworkCore;
using Exam_Helper.ViewsModel;

namespace Exam_Helper.Controllers
{
    public class PacksLibController : Controller
    {
        //private readonly 
        DbContext _context = new DbContext();

        //public PacksLibController(DbContext context)
        //{
        //    _context = context;
        //}

        public PacksLibController()
        {

        }

        // GET: PacksLib
        public async Task<ActionResult> Index()
        {
            return View(await _context.Pack.ToListAsync());
        }

        // GET: PacksLib/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var pack = await _context.Pack
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pack == null)
            {
                return HttpNotFound();
            }

            return View(pack);
        }

        // GET: PacksLib/Create
        public async Task<ActionResult> Create()
        {
            var ques = await _context.Question.Select(x => new QuestionForPackCreatingModel()
            { Id = x.Id, Name = x.Title, IsSelected = false }).ToListAsync();
            var tags = await _context.Tags.Select(x => new TagForPackCreatingModel()
            { Id = x.Id, Name = x.Title, IsSelected = false }).ToListAsync();

            return View(new ClassForPackCreatingModel() { questions = ques, pack = new Pack(), tags = tags});
        }

        // POST: PacksLib/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClassForPackCreatingModel obj)
        {    
            Pack pack = new Pack();
            if (ModelState.IsValid)
            {
                
                var ques = obj.questions.Where(x => x.IsSelected).Select(x=>x.Id);
                var StringIds = string.Join(";", ques);

                var tags = obj.tags.Where(x => x.IsSelected).Select(x => x.Id);
                var TagsIds = string.Join(";", tags);

                pack.Name = obj.pack.Name;
                pack.UpdateDate = DateTime.Now;
                pack.CreationDate = DateTime.Now;
                pack.Author = "Admin";
                pack.QuestionSet = StringIds;
                pack.TagsId = TagsIds;
                _context.Add(pack);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            
            return View(pack);
        }

        // GET: PacksLib/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            
            var pack = await _context.Pack.FindAsync(id);
            if (pack == null)
            {
                return HttpNotFound();
            }
            return View(pack);
        }  

        // POST: PacksLib/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Pack pack)
        {
            if (id != pack.Id)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var old = await _context.Pack.AsNoTracking().FirstAsync(x => x.Id == id);
                    pack.CreationDate = old.CreationDate;
                    pack.UpdateDate = DateTime.Now;
                    _context.Update(pack);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PackExists(pack.Id))
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pack);
        }

        // GET: PacksLib/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var pack = await _context.Pack
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pack == null)
            {
                return HttpNotFound();
            }

            return View(pack);
        }

        // POST: PacksLib/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var pack = await _context.Pack.FindAsync(id);
            _context.Pack.Remove(pack);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PackExists(int id)
        {
            return _context.Pack.Any(e => e.Id == id);
        }
    }
}

Exam_Helper/Views/PacksLib/Create.cshtml
@model Exam_Helper.ViewsModel.ClassForPackCreatingModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h1>Create</h1>

    <h4>Pack</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.pack.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.pack.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.pack.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.questions, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @for (int i = 0; i < Model.questions.Count; i++)
                        {
                            <li>
                                @Html.CheckBoxFor(model => Model.questions[i].IsSelected)
                                @Html.Label(Model.questions[i].Name)
                                @Html.HiddenFor(model => model.questions[i].Id)
                                @Html.HiddenFor(model => model.questions[i].Name)
                            </li>
                        }
                    </div>
                </div>
                <!--hidden
            <div class="form-group">
            <label asp-for="@Model.pack.Author" class="control-label"></label>
            <input asp-for="@Model.pack.Author" class="form-control" />
            <span asp-validation-for="@Model.pack.Author" class="text-danger"></span>
        </div>
        -->

                <div class="form-group">
                    @Html.LabelFor(model => model.tags, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @for (int i = 0; i < Model.tags.Count; i++)
                        {
                            <li>
                                @Html.CheckBoxFor(model => Model.tags[i].IsSelected)
                                @Html.Label(Model.tags[i].Name)
                                @Html.HiddenFor(model => model.tags[i].Id)
                                @Html.HiddenFor(model => model.tags[i].Name)
                            </li>
                        }
                    </div>
                </div>

                <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Exam_Helper/Views/PacksLib/Index.cshtml
@model IEnumerable<Exam_Helper.Pack>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <!--
    <a asp-action="Create">
        <button type="button" class="btn btn-warning bd-highlight">Добавить Пак</button>
    </a>
    -->
    @Html.ActionLink("Добавить Пак", "Create", "PacksLib", new { type = "button" }, new { @class = "btn btn-warning bd-highlight" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuestionSet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TagsId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionSet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate.GetDateTimeFormats()[0])
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate.GetDateTimeFormats()[0])
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TagsId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>